WorldPopulation=read.csv("data-raw/jhu-worldpop.csv")
USArea=read.csv("data-raw/census-state-area.csv")
G20=read.csv("data-raw/G20.csv")
USPopulation=read.csv("data-raw/jhu-statepop.csv")
WorldArea=read.csv("data-raw/jhu-worldarea.csv")
States50=read.csv("data-raw/States50.csv")

use_data(WorldPopulation, overwrite = T)
use_data(USArea, overwrite = T)
use_data(G20, overwrite = T)
use_data(USPopulation, overwrite = T)
use_data(WorldArea, overwrite = T)
use_data(States50, overwrite = T)
